# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
 branches:
   include:
     - main
   exclude:
     - feature/*
     - develop
     - release
     - bugfix

pool:
 name: "pool-1"

 demands:
  - maven
  - java

#variables:
  # Container registry service connection established during pipeline creation
   #dockerRegistryServiceConnection: '6246b5be-821b-416d-a526-1b27edb83a94'
  #imageRepository: 'abuildpackimagev10'
  #containerRegistry: 'repo122.azurecr.io'
  #dockerfilePath: '$(Build.SourcesDirectory)/dockerfile'
  #tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and SonarQube Analysis
  jobs:
  - job: Build
    displayName: Build
    steps:
     - task: SonarQubePrepare@7
       inputs:
         SonarQube: 'ado-sq-svc-connection'
         scannerMode: 'other'
         extraProperties: |
           # Additional properties that will be passed to the scanner,
           # Put one key=value per line, example:
           # sonar.exclusions=**/*.bin
           sonar.projectKey=payment_payment_79054d2d-71ea-45e9-a7ae-4478d2a329c3
           sonar.projectName=payment
     - task: Maven@4
       inputs:
         azureSubscription: 'Azure subscription 1(cacb9864-459f-41eb-b7dd-bfe56cd25dc3)'
         mavenPomFile: 'pom.xml'
         publishJUnitResults: true
         testResultsFiles: '**/surefire-reports/TEST-*.xml'
         javaHomeOption: 'JDKVersion'
         mavenVersionOption: 'Default'
         mavenAuthenticateFeed: false
         effectivePomSkip: false
         sonarQubeRunAnalysis: true
         sqMavenPluginVersionChoice: 'pom'
         
     

     - task: SonarQubePublish@7
       inputs:
         pollingTimeoutSec: '300'