apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildpacks-deployment
  labels:
    app: buildpacks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: buildpacks
  template:
    metadata:
      labels:
        app: buildpacks
    spec:
      containers:
        - name: buildpacks-container
          image: buildpacksacr.azurecr.io/buildpacks-image:V6.0
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: acr-auth-secret

apiVersion: v1
kind: Service
metadata:
  name: buildpack-service
spec:
  type: LoadBalancer
  selector:
    app: buildpack
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 #conainer port becomes target port

